### ISSUE TITLE
workflow running problem

### ISSUE THREAD

**Issue by aslangabriel** [brinkmanlab/IslandCompare#228]
Hi, I have imported workflow and installed each tools via toolshed in galaxy platform. But it still prompted error message of Following tools missing: __APPLY_RULES__.  Unfortunately，there is no such tool in the repository. Would you like to fix this problem or give some workarounds?

**Comment by innovate-invent** [comment]
Hi and thank you for your interest in IslandCompare.

APPLY_RULES is a tool that is included with Galaxy, if you have modified the [tool_conf.xml](https://github.com/galaxyproject/galaxy/blob/ee02bbcefdf3e4fdfc3673868c332447503803c1/lib/galaxy/config/sample/tool_conf.xml.sample#L41) you may have disabled it.

We also provide a means of automatically deploying Galaxy and the workflow to either a local docker deployment, or AWS Cloud.
