### ISSUE TITLE
galaxy workflow running problem

### ISSUE THREAD

**Issue by aslangabriel** [brinkmanlab/IslandCompare#229]
Hi, I have imported islandcompare.ga into my workflow and installed all the tools needed. My problem is should I upload CARD databases or other related GI dataset to prepare for the ananlysis. For I tried running on web hosted in Canada and the prcocess stucked by the inital uploading stage which just upload 4 gff files with 20 unsucessful for unknow reasons. Thanks for youf time.

**Comment by innovate-invent** [comment]
Hi and thank you for your interest in IslandCompare. You are right, I appear to have omitted the data_manager tool configuration in the manual setup instructions. 

I will update those ASAP. In the meantime, you can try and use the terraform deployment module for Galaxy. It will automatically install everything needed.

**Comment by innovate-invent** [comment]
I have updated the instructions. Please let me know if there is anything else missing.
